### PR TITLE
Resolve #170 Add CSV Endpoint

### LINKED ISSUE #170: CSV Downloads Do Not Work
**Describe the bug**
As part of switching to PRQL the CSV downloads are not working. We need to make a CSV endpoint in Rack to get this working.

### PR DESCRIPTION
**Pull request by mzagaja**
Resolves #170.

# Why is this change necessary?
Users would like to download CSV files and the move to PRQL has removed this feature.

# How does it address the issue?
It adds an endpoint to data common to allow for CSV downloads of datasets

# What side effects does it have?
None.

### CODE REVIEW

File: app/csv.rb [hunk 1]
```diff
@@ -21,14 +21,14 @@ def each(&blk)
...
-    def to_csv(table_name)
+    def to_csv(table_name, database_name)
       template = ERB.new File.new("config/settings.yml").read
       @settings = YAML.load template.result(binding)
 
       file_name = "export-#{table_name}-#{Time.now.to_i}.csv"
       arguments = []
       arguments << %Q(-c "\\copy (SELECT * FROM #{table_name}) to 'public/#{file_name}' with csv")
-      arguments << %Q(-w -h #{@settings['database']['host']} -p #{@settings['database']['port']} -U #{@settings['database']['username']} -d #{@settings['database']['tabular']['database']})
+      arguments << %Q(-w -h #{@settings['database']['host']} -p #{@settings['database']['port']} -U #{@settings['database']['username']} -d #{database_name})
```
Comment (iangmhill) [inline app/csv.rb]: Can we whitelist database names?
