### PR TITLE
Download selected years

### LINKED ISSUE #193: Data Browser should only download data for years selected
**Describe the bug**
When downloading datasets, all years are downloaded instead of just the ones selected/filtered by the user. If a user is only selecting the years that they view, they should expect that they are only downloading the data they need. This is extremely problematic for some of our more massive datasets where a user only needs the current year instead of hundreds of megabytes extra. 

**Steps to reproduce**
1. Navigate to https://datacommon.mapc.org/browser/datasets/3
2. Observe years selected/filtered/displayed
3. Click the CSV download button to upper right hand of table
4. Open downloaded CSV
5. Observe that all possible years have been downloaded regardless of the state of the interface. 

**Expected behavior**
The CSV download should only include years selected/filtered/displayed.

### PR DESCRIPTION
**Pull request by ericyoungberg**
Resolves #193.

# Why is this change necessary?
The original intent of the download was that the browser should only be downloading data by the selectable year filters on the site. 

# How does it address the issue?
It checks for year values before resolving the query arguments. If the `years` and `year_col` params exist, then the data will be filtered by years selected.

# What side effects does it have?
The results of a year query are stored in the warmed cache.

### CODE REVIEW

File: app/csv.rb [hunk 1]
```diff
@@ -20,34 +21,55 @@ def each(&blk)
   end
 
   class API
+    @@cache_dir = 'public/cache'
```
Comment (mzagaja) [inline app/csv.rb]: If we're abstracting it into something that can be defined at the top of the class, should this be a constant instead of a class variable? 
http://rubylearning.com/satishtalim/ruby_constants.html
