### PR TITLE
Match exact counts for height/width on styling and element attribute

### LINKED ISSUE #284: Homepage sliced header discrepancies
**Describe the bug**
On some page loads, the sliced portion of the header does not appear as expected. It stops about 4/5 of the way across the screen and goes all the way to the top (creating a triangle of particles instead of a trapezoid)

**Steps to reproduce**
I haven't been able to nail down a definitive reproduction pattern, but it does consistently seem to happen on browser resizing and on the first load of the page. Going to another page and then clicking back to the homepage loads the page as expected.

**Screenshots**
Expected:
Screen Shot 2020-03-02 at 11 04 24 AM

Experienced:
image

**Desktop (please complete the following information):**
- OS: Windows10
- Browser: IE11
- Version: 11.0.9600.19597

- OS: MacOS Catalina
- Google Chrome 80.0.3987.122, Firefox 73.0.1 (64-bit), Safari Version 13.0.5 (15608.5.11)

### PR DESCRIPTION
**Pull request by atomtay**
Resolves #284 .

# Why is this change necessary?
On some renderings of the Particles component, the height was off. This resulted in the canvas elements appearing distorted and the sliced triangle taking up too much space.

# How does it address the issue?
- Determine the exact height and width based on innerWidth and, additively, how much space the font + padding takes
- Assign this value for both the canvas height/width attributes (how many pixels should go into the element) and the height/width style (how many pixels that space should take up); this mismatch was causing the distortion

# What side effects does it have?
I took this as an opportunity to refactor the random number generator so that dots always stayed within the bounds of the canvas. Now, the dots don't all seem to disappear after a minute.

### CODE REVIEW

File: app/javascript/pages/components/partials/Particles.jsx [hunk 1]
```diff
@@ -164,17 +161,30 @@ class Particles extends React.Component {
...
 
   updateDimensions() {
-    this.setState({ width: window.innerWidth });
+    this.setState(() => {
+      const newWidth = window.innerWidth;
+      let newHeight = 421;
+      if (newWidth <= 770) {
+        newHeight = 221;
+      }
+      return { width: newWidth, height: newHeight };
```
Comment (mzagaja) [inline app/javascript/pages/components/partials/Particles.jsx]: I think you can also rewrite as: 

```javascript
return {
  width: window.innerWidth
  height: window.innerWidth <= 770 ? 221 : 421// not sure if you need parens for some of this though
}
```

Comment (atomtay) [reply app/javascript/pages/components/partials/Particles.jsx]: One of these days I'll remember that the ternary operator exists but apparently that day is not today (and tomorrow isn't looking too good, either). Updated.
